<?php

return [
    'page_format'           => 'A4',
    'page_orientation'      => 'P',
    'page_units'            => 'mm',
    'unicode'               => true,
    'encoding'              => 'UTF-8',
    'font_directory'        => '',
    'image_directory'       => public_path('vendor/tecnickcom/tcpdf/examples/images/'),
    'tcpdf_throw_exception' => false,
    'use_fpdi'              => false,
    'use_original_header'   => false,
    'use_original_footer'   => false,
    'pdf_header_logo'       => '',
    'pdf_header_logo_width' => 30,
    'pdf_header_title'      => 'تقرير',
    'pdf_header_string'     => '',
    'pdf_header_font'       => 'dejavusans',
    'pdf_footer_font'       => 'dejavusans',
    'pdf_monospaced_font'   => 'courier',
    'pdf_page_format'       => 'A4',
    'pdf_page_orientation'  => 'P',
    'pdf_creator'           => 'TCPDF',
    'pdf_author'            => 'TCPDF',
    'pdf_header_title'      => '',
    'pdf_header_string'     => '',
    'pdf_unit'              => 'mm',
    'k_cell_height_ratio'   => 1.25,
    'k_title_magnification' => 1.3,
    'k_small_ratio'         => 2/3,
    'k_thai_topchars'       => true,
    'k_tcpdf_calls_in_html' => false,
    'k_tcpdf_external_config'=> false,
];
