<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * Spec 003 FR-203 — one scheduled installment of a LeaseContract, generated by
 * LeaseScheduleGenerator and updated as payments are made / alerts fire.
 */
class LeasePayment extends Model
{
    protected $table = 'lease_payments';

    protected $fillable = [
        'contract_id', 'payment_no', 'due_date', 'amount',
        'status', 'paid_date', 'paid_amount', 'remaining', 'penalty', 'note',
    ];

    protected $casts = [
        'contract_id' => 'integer',
        'payment_no' => 'integer',
        'due_date' => 'date',
        'amount' => 'decimal:2',
        'paid_date' => 'date',
        'paid_amount' => 'decimal:2',
        'remaining' => 'decimal:2',
        'penalty' => 'decimal:2',
    ];

    public function contract(): BelongsTo
    {
        return $this->belongsTo(LeaseContract::class, 'contract_id');
    }
}
